name: Auto LinkedIn Post Generation

on:
  schedule:
    # Runs at 8 AM and 8 PM UTC daily
    - cron: '0 8,20 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify the Python version you need

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        python -m spacy download en_core_web_sm
        python -m spacy download en_core_web_md

    - name: Run the Script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        LINKEDIN_CLIENT_ID: ${{ secrets.LINKEDIN_CLIENT_ID }}
        LINKEDIN_CLIENT_SECRET: ${{ secrets.LINKEDIN_CLIENT_SECRET }}
        LINKEDIN_AUTH_TOKEN: ${{ secrets.LINKEDIN_AUTH_TOKEN }}
        LINKEDIN_REDIRECT_URI: ${{ secrets.LINKEDIN_REDIRECT_URI }}
        LINKEDIN_VISIBILITY: ${{ secrets.LINKEDIN_VISIBILITY }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        python main.py
